name: lint_python
on:
  pull_request:
    branches: [master, enum_monkey_patch_for_micropython]
  push:
    branches: [master, enum_monkey_patch_for_micropython]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install tox
      - run: tox -e lint
